name: Release

on:
  push:
    tags:
      - '*'

jobs:
  github:
    name: 'GitHub Release'
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT

      - name: Checkout sources
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install dependent packages
        run: sudo apt install -y musl-tools

      - run: rustup update stable
      - run: rustup default stable
      - run: rustup target add x86_64-unknown-linux-musl
      - name: Install cross
        run: cargo install cross
      - name: Run cargo build for Linux
        run: cargo build --release --target=x86_64-unknown-linux-musl
      - name: Run cargo build for Windows
        run: cross build --release --target x86_64-pc-windows-gnu

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ steps.get_version.outputs.VERSION }} \
            --title "v${{ steps.get_version.outputs.VERSION }}" \
            --generate-notes

      - name: Upload Linux Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mv target/x86_64-unknown-linux-musl/release/funst funst-${{ steps.get_version.outputs.VERSION }}.linux-amd64
          gh release upload ${{ steps.get_version.outputs.VERSION }} \
            funst-${{ steps.get_version.outputs.VERSION }}.linux-amd64

      - name: Upload Windows Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mv target/x86_64-pc-windows-gnu/release/funst.exe funst-${{ steps.get_version.outputs.VERSION }}.exe
          gh release upload ${{ steps.get_version.outputs.VERSION }} \
            funst-${{ steps.get_version.outputs.VERSION }}.exe
